name: Deploy-SSH-Workflow

on:
    push:
        branches: ['workflow']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      set -e

                      echo "Set variables"
                      DEPLOY_DIR="$HOME/repos"
                      REPO_NAME="${{ github.event.repository.name }}"
                      BRANCH_NAME="${{ github.ref_name }}"

                      echo "Go to $DEPLOY_DIR/$REPO_NAME and pull repository"
                      cd "$DEPLOY_DIR/$REPO_NAME"
                      git fetch origin "$BRANCH_NAME"
                      git checkout "$BRANCH_NAME"
                      git pull origin "$BRANCH_NAME"
                      git submodule update --init --recursive

                      echo "Stop Docker container"
                      docker compose down || true

                      echo "Start Docker container"
                      docker compose up -d

                      echo "Deployment completed"
