name: Deployment-SSH-Workflow

on:
    push:
        branches: ['workflow']
        tags:
            - 'v*.*.*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3.4.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Backend image
            - name: Extract metadata (tags) for backend
              id: meta-backend
              uses: docker/metadata-action@v3.4.0
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-backend
                  tags: |
                      type=semver, pattern={{version}}
                      type=sha

            - name: Build and push backend image
              id: push-backend
              uses: docker/build-push-action@v6.18.0
              with:
                  context: ./conduit-backend
                  file: Dockerfile
                  push: true
                  tags: ${{ steps.meta-backend.outputs.tags }}

            # Frontend image
            - name: Extract metadata (tags) for frontend
              id: meta-frontend
              uses: docker/metadata-action@v3.4.0
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-frontend
                  tags: |
                      type=semver, pattern={{version}}
                      type=sha

            - name: Build and push frontend image
              id: push-frontend
              uses: docker/build-push-action@v6.18.0
              with:
                  context: ./conduit-frontend
                  file: Dockerfile
                  push: true
                  tags: ${{ steps.meta-frontend.outputs.tags }}

    deploy:
        name: Deploy to VM via SSH
        runs-on: ubuntu-latest
        needs: build-and-push-image

        steps:
            - name: Prepare docker compose file
              run: |
                  export BACKEND_IMAGE=ghcr.io/…:${{ steps.meta-backend.outputs.tags }}
                  export FRONTEND_IMAGE=ghcr.io/…:${{ steps.meta-frontend.outputs.tags }}
                  envsubst < docker-compose.yaml > compose-deploy.yml

            - name: Copy docker compose to VM via SSH
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: compose-deploy.yml
                  target: '$HOME/repos/${{ github.repository }}/docker-compose.yaml'

            - name: Run rocker compose file
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      set -e
                      echo "${{ secrets.GITHUB_TOKEN }}" \
                        | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                      cd "$HOME/repos/${{ github.repository }}"
                      docker compose pull
                      docker compose down
                      docker compose up -d

                      echo "Deployment completed successfully!"
